In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

numpy digunakan untuk komputasi numerik

matplotlib digunakan untuk grafik/ploting

pandas digunakan untuk memanggil file external dari csv,xslx,txt,dll

In [5]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(x)

[['France' 40.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
print (y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy= 'mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [11]:
print(x)

[['France' 40.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.333333333333336 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [47]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [48]:
print (x)

[[1.0 0.0 0.0 40.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.333333333333336 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [49]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [50]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)


In [52]:
print(x_train)

[[0.0 0.0 1.0 38.333333333333336 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 40.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [53]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [54]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [55]:
print(y_test)

[0 1]


In [56]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [57]:
print(x_train)

[[0.0 0.0 1.0 -0.17935780752172312 -1.0781259408412425]
 [0.0 1.0 0.0 0.06803227181858379 -0.07013167641635372]
 [1.0 0.0 0.0 0.06803227181858379 0.633562432710455]
 [0.0 0.0 1.0 -0.22883582338978492 -0.30786617274297867]
 [0.0 0.0 1.0 -1.861610347035813 -1.420463615551582]
 [1.0 0.0 0.0 1.2555046526520586 1.232653363453549]
 [0.0 1.0 0.0 1.5523727478604274 1.5749910381638885]
 [1.0 0.0 0.0 -0.674137966202338 -0.5646194287757332]]


In [58]:
print(x_test)

[[0.0 1.0 0.0 -1.4163082042232598 -0.9069571034860727]
 [1.0 0.0 0.0 -0.3772698709939693 0.2056403393225306]]
